# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Compile Code

on:
  push:
    branches: "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt
      - name: Install dependencies
        run: sudo apt install -y pngquant findutils xvfb
      - name: Hack Forge Gradle
        run: mkdir -p ~/.gradle/caches/minecraft/; wget 'https://teamopenindustry.cc/maven/hack/ForgeGradleVersion.json' -O ~/.gradle/caches/minecraft/ForgeGradleVersion.json
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Universal Mod Core (and helpers)
        run: ./gradlew umc -D umc.loader=1.12.2-forge -D ssh.http=true
      - name: Gradle compile
        run: ./gradlew classes
      - name: Process images
        run: find src/main/resources/assets/landofsignals/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
      - name: Run Data (optionalish)
        run: xvfb-run --auto-servernum ./gradlew runData || xvfb-run --auto-servernum ./gradlew runData || true
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ImmersiveTracks 1.12.2-forge
          path: build/libs/ImmersiveTracks-1.12.2-forge-*